### ISSUE TITLE
please retag "1.1.0" as "v1.1.0"

### ISSUE THREAD

**Issue by majewsky** [surma/gocpio#6]
go.mod only uses tags that have the "v" in front, so it defaults to pulling version 1.0.1 instead of 1.1.0.

**Comment by evelikov** [comment]
@surma can you please add a "v1.1.0" tag, the existing "1.1.0" can stay as-is. Thanks

**Comment by obbardc** [comment]
@surma bump :-)

**Comment by obbardc** [comment]
tag `v1.1.0` now exists in this repository!
